# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Desktop
# layerrule {
#   name = swaync_layer_center
#   blur = on
#   ignore_alpha = 0.3
#   match:namespace = swaync-control-center
# }
#
# layerrule {
#   name = swaync_layer_window
#   blur = on
#   ignore_alpha = 0.3
#   match:namespace = swaync-notification-window
# }


# laptop-desktop
windowrule {
  name = rofi_window_rl
  float = on
  match:class = ^(Rofi)$
  match:title = ^(rofi - drun)$
}

windowrule {
  name = btop_window_rl
  float = on
  match:class = ^(foot)$
  match:title = ^(btop)|(btop).[~/Z-a]$
}

windowrule {
  name = countdown_window_rl
  float = on
  match:class = ^(foot)$
  match:title = ^(countdown)|(termdown)$
}

windowrule {
  name = godot_window_rl
  group = deny
  match:class = ^(Godot)$
  match:title = ^(Game Workspace - Godot Engine)$
}


windowrule {
  name = steam_window_rl
  no_focus = on
  min_size = 1 1
  match:title = ^()$
  match:class = ^(steam)$
}

