# See https://wiki.hyprland.org/Configuring/Monitors/

# DESKTOP
  $monitor0 = DP-1
  # $monitor0 = DP-3
  $monitor1 = DP-2
  monitor= $monitor0,2560x1440@180,0x0,1,vrr,1
  # monitor= $monitor1,1600x900@60,2560x0,1
  #
  workspace = 1, monitor:$monitor0
  workspace = 2, monitor:$monitor1
  # workspace = 3, monitor:$monitor0
  # workspace = 4, monitor:$monitor1

# laptop
  # $monitor0 = eDP-1
  # $monitor1 = HDMI-A-1
  # monitor= $monitor0,1920x1080,0x0,1
  # monitor= $monitor1,1920x1080@75,1600x0,1

  # workspace = $monitor0,1
  # workspace = $monitor1,2
  # workspace = $monitor0,3
  # workspace = $monitor1,4
